#配置dev环境
spring:
  profiles: dev
  application: abcms-eurekaServer-config
server:
  port: 8400
eureka:
  instance:
    hostname: eureka8400.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka8400:8400/eureka
---
#配置test环境
#配置dev环境
spring:
  profiles: test
  application: abcms-eurekaServer-config
server:
  port: 8500
eureka:
  instance:
    hostname: eureka8500.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka8500:8500/eureka